// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xefhzszlzvfgvosomyxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZmh6c3psenZmZ3Zvc29teXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjI1NjUsImV4cCI6MjA2NzA5ODU2NX0.H2NFdRlV_aJzhOjf_bHfI6uQTRFxOkb61Vsutyn5S9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});